version: '3'

services:
  redis:
    image: redis
    container_name: redis
    expose:
    - 6379
  api:
    build: ./
    volumes:
    - ./:/var/www/app
    links:
    - redis
    ports:
    - 3000:3000
    environment:
    - REDIS_URL=redis://redis
    - NODE_ENV=development
    - PORT=3000
    command:
      sh -c 'npm i && node server.js'
