version: '3'

services:
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    container_name: redis
    expose:
      - 6379
    networks:
       - process-monitoring_monitoring_1
    sysctls:
      net.core.somaxconn: 1024
    volumes:
    - redis-data:/data

  api:
    build: ./
    volumes:
      - ./:/var/www/app
    links:
      - redis
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - redis
    networks:
      - process-monitoring_monitoring_1
    command:
      sh -c 'npm i && node server.js'

volumes:
 redis-data:
networks:
  process-monitoring_monitoring_1:
    external: true
