version: '3'

services:
  elasticsearch:
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
      - xpack.security.enabled=false
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    networks:
      - monitoring_1
    ports:
    - 9200:9200
    expose:
      - 9200
    restart: unless-stopped
#    volumes:
#    - elasticsearch:/usr/share/elasticsearch/data:rw

  logstash:
    build:
      context: ./logstash
    volumes:
     - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
     - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - monitoring_1
    depends_on:
      - elasticsearch

  kibana:
    depends_on:
    - elasticsearch
    environment:
      http.host: 0.0.0.0
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
    image: docker.elastic.co/kibana/kibana-oss:6.2.1
    networks:
      - monitoring_1
    ports:
    - 5601:5601
    restart: unless-stopped

#volumes:
# elasticsearch:
#   driver: local

networks:
  monitoring_1:
    driver: bridge
